variable "name" {}
variable "location" {}
variable "env" {}
variable "address_space" {}
variable "address_prefixes1" {}
variable "address_prefixes2" {}
variable "identity" {}
variable "kubernetes_version" {}
variable "node-group-name" {}
variable "sku_tier" {}
variable "service_cidr" {}
variable "dns_service_ip" {}